#!/usr/bin/env bash
# cao-entrypoint — start one CAO node inside a container.
#
# In this EKS one-agent-per-pod topology, the same entrypoint serves two
# roles distinguished purely by env: the SUPERVISOR pod (code_supervisor
# profile, CAO_ADVERTISED_URL set, no terminal cap) delegates work to WORKER
# pods (worker profile, CAO_MAX_TERMINALS=1 — exactly one agent per pod) via
# the assign/handoff `target_host` parameter.
#
# Env:
#   CAO_BIND_HOST         bind address for cao-server (default 0.0.0.0 —
#                         container networking is expected to gate access;
#                         see the security note below)
#   CAO_API_PORT          server port (default 9889)
#   CAO_ALLOWED_HOSTS     comma-separated extra Host-header values (set this to
#                         the container/pod DNS name peers will use to reach it)
#   CAO_INSTALL_PROFILES  optional space-separated "profile:provider" pairs to
#                         install before the server starts,
#                         e.g. "code_supervisor:claude_code developer:claude_code"
#                         Pairs already present in the baked state seed are
#                         skipped — see the seed block below.
#   CAO_WARM_PROVIDER     provider preflight mode:
#                           1 / unset  run it and BLOCK until it finishes
#                                      (default — readiness then implies warm)
#                           background run it AFTER the server is exec'd, so it
#                                      never delays readiness
#                           0          skip it entirely
#   CAO_STATE_SEED        path to a tar of a pre-initialized CAO_HOME_DIR, baked
#                         into the image. Extracted in place of `cao init` when
#                         the state directory is empty.
#   CAO_STATE_SEED_ROOT   the CAO_HOME_DIR the seed was built for. The seed is
#                         only used when CAO_HOME_DIR matches it exactly.
#   CAO_MAX_TERMINALS     optional cap on terminals this node will track
#                         (unset = unlimited). Worker pods set 1 so each pod
#                         hosts exactly one agent; extra placements get HTTP 429.
#   CAO_ADVERTISED_URL    base URL at which PEERS can reach this node's
#                         cao-server (e.g. http://cao-supervisor:9889). Set on
#                         the supervisor pod so remote workers' send_message
#                         callbacks can route results back cross-pod.
#
# SECURITY: cao-server has no per-request auth by default. Anyone who can reach
# the port can launch agents (command execution) in this container. Restrict
# reachability with Docker networks / k8s NetworkPolicy, or enable CAO's OAuth
# layer (AUTH0_DOMAIN / CAO_AUTH_JWKS_URI).
set -euo pipefail

BIND_HOST="${CAO_BIND_HOST:-0.0.0.0}"
PORT="${CAO_API_PORT:-9889}"

# State seed — replace `cao init` + `cao install` with a tar extract.
#
# In the elastic topology the state directory is a fresh emptyDir on EVERY task,
# so this whole block is on the critical path of every delegation, not just of a
# cold start. Measured on the pinned image: `cao init` (schema migrations,
# startup memory repair, copying 12 bundled skill trees) takes ~1.9s and each
# `cao install` another ~1.9s — around 3.8s of a 22s placement spent producing a
# tree that is byte-identical every time.
#
# So it is produced once at BUILD time (Dockerfile) and extracted here.
# Three conditions, all of them load-bearing:
#
#   - the seed exists. Absent (an older image, or a plain `docker build` of an
#     earlier Dockerfile) the code below falls through to `cao init` unchanged.
#   - CAO_HOME_DIR is exactly the path the seed was built for. Today's seed is
#     in fact relocatable — the DB is schema-only with zero rows and no file in
#     it contains an absolute path — so this guard is not what makes the extract
#     correct right now. It is here to keep that a CHECKED property rather than a
#     coincidence: the seed carries a SQLite DB and provider context files, and
#     the day one of them records a path, a mismatched root would fail somewhere
#     no one traces back to a tar extract in an entrypoint.
#   - the state directory is empty. The supervisor's state is a PVC that
#     survives restarts, so seeding it on a restart would clobber real work.
#     The worker's is an emptyDir, so it is always empty and always seeded.
#
# Schema drift is not a risk the way it would be for a checked-in fixture: the
# seed is generated by the same `cao` that reads it, in the same image layer, so
# the two cannot disagree about migrations.
CAO_STATE_SEED="${CAO_STATE_SEED:-}"
CAO_STATE_SEED_ROOT="${CAO_STATE_SEED_ROOT:-}"
seeded=0

if [ -n "${CAO_STATE_SEED}" ] && [ -f "${CAO_STATE_SEED}" ] \
   && [ -n "${CAO_STATE_SEED_ROOT}" ] \
   && [ "${CAO_HOME_DIR:-}" = "${CAO_STATE_SEED_ROOT}" ] \
   && [ -z "$(ls -A "${CAO_HOME_DIR}" 2>/dev/null || true)" ]; then
  seed_parent="$(dirname "${CAO_STATE_SEED_ROOT}")"
  mkdir -p "${seed_parent}"
  if tar -xf "${CAO_STATE_SEED}" -C "${seed_parent}"; then
    seeded=1
    echo "[cao-entrypoint] state seeded from ${CAO_STATE_SEED} (skipping cao init)"
  else
    # Refuse to trust a partial extract: a half-written DB is worse than a slow
    # start, and `cao init` below is idempotent over whatever landed.
    echo "[cao-entrypoint] WARN: state seed failed to extract; falling back to cao init"
  fi
fi

if [ "${seeded}" = "0" ]; then
  echo "[cao-entrypoint] initializing CAO state"
  cao init || true
fi

# Is this profile already installed for this provider?
#
# `cao install --provider X` records the resolved provider back into the local
# store copy's frontmatter, which is precisely what the seed captures. Matching
# on that line rather than on file existence matters: a profile present but
# pinned to a DIFFERENT provider must be reinstalled, because a delegation
# resolves the provider from the TARGET node's store and a wrong pin fails by
# naming a CLI nobody asked for.
profile_installed() {
  store="${CAO_HOME_DIR:-}/agent-store/${1}.md"
  [ -f "${store}" ] && grep -qE "^provider:[[:space:]]*${2}[[:space:]]*$" "${store}"
}

if [ -n "${CAO_INSTALL_PROFILES:-}" ]; then
  for spec in ${CAO_INSTALL_PROFILES}; do
    profile="${spec%%:*}"
    provider="${spec##*:}"
    if profile_installed "${profile}" "${provider}"; then
      echo "[cao-entrypoint] profile '${profile}' already installed for '${provider}' (seeded)"
      continue
    fi
    echo "[cao-entrypoint] installing profile '${profile}' for provider '${provider}'"
    cao install "${profile}" --provider "${provider}" \
      || echo "[cao-entrypoint] WARN: install ${spec} failed (continuing)"
  done
fi

# Provider preflight — one throwaway model call per pinned tier.
#
# This is not a health check, it is a warm-up, and it exists because of two
# behaviours that otherwise both land on the first real prompt:
#
#   1. The first invocation of an Anthropic model in an account that has not
#      activated it makes Bedrock auto-initiate an AWS Marketplace subscription.
#      Activation can take up to two minutes, during which calls fail with a 403
#      naming marketplace actions. Paying that cost here, while the pod is
#      starting anyway, keeps it off the critical path.
#   2. Every distinct model needs its own activation, so this warms each pinned
#      tier rather than just the primary.
#
# Non-fatal on purpose, and note that `|| true` is doing real work under
# `set -euo pipefail`: an exit 127 anywhere in a pipeline becomes the pipeline's
# status, so a missing binary would otherwise kill the container. A pod that
# cannot reach Bedrock should still start and report a clear error to an operator
# rather than crash-looping with the reason buried in a previous container's log.
warm_one() {
  model_var="$1"
  model="$2"
  log="/tmp/warm.${model_var}.log"
  echo "[cao-entrypoint] warming ${model_var}=${model}"
  if ANTHROPIC_MODEL="${model}" timeout 180 claude -p "Reply with the single word: ok" \
       >"${log}" 2>&1; then
    echo "[cao-entrypoint] ${model_var} responded: $(tr -d '\n' < "${log}" | tail -c 120)"
  else
    echo "[cao-entrypoint] WARN: ${model_var} did not respond; first real prompt may be slow or fail"
    echo "[cao-entrypoint] WARN: $(tr -d '\n' < "${log}" | tail -c 300)"
  fi
  rm -f "${log}" || true
}

# Warm every pinned tier CONCURRENTLY.
#
# The tiers are independent — a separate marketplace activation and a separate
# round trip each — and the cost is almost entirely waiting on Bedrock, not local
# CPU. Serially they measured 3.6s + 4.6s = 8.3s of an ~18s pod readiness; run
# together they cost the slower of the two.
#
# Each call writes to its own log file: two `claude` processes sharing one would
# interleave, and the WARN branch below would then quote a mixture of both.
warm_all() {
  pids=""
  for model_var in ANTHROPIC_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL; do
    model="${!model_var:-}"
    [ -n "${model}" ] || continue
    warm_one "${model_var}" "${model}" &
    pids="${pids} $!"
  done
  for pid in ${pids}; do
    wait "${pid}" || true
  done
}

warm_mode="${CAO_WARM_PROVIDER:-1}"
if [ "${CLAUDE_CODE_USE_BEDROCK:-}" != "1" ]; then
  warm_mode="0"
fi

case "${warm_mode}" in
  0|no|false)
    ;;
  background|bg)
    # Warm-up AFTER the server is up, for pods whose creation latency a human is
    # watching — in the elastic topology that is every worker, on every task.
    #
    # This drops the warm-up out of the readiness path entirely rather than just
    # shortening it. What is given up is the implication "Ready therefore warm",
    # and it is worth being precise about the cost: warm-up was ALREADY
    # non-fatal, so no pod has ever failed to become Ready because a model was
    # cold, and nothing that used to be enforced stops being enforced here. What
    # can now happen is that a task arrives before the warm-up returns. Marketplace
    # activation is per ACCOUNT, so on a fleet whose supervisor warmed the same
    # model ids at provisioning that costs a cold CLI start, not two minutes of
    # activation. A fleet where a worker might be the first caller in the account
    # should keep the blocking default.
    #
    # `&` before `exec`: the subshell outlives the shell that spawned it, and
    # inherits this container's stdout, so its lines still land in `kubectl logs`.
    # It is reparented to cao-server, which does not reap children it did not
    # create, so it lingers as a zombie holding one PID slot for the life of the
    # pod. Exactly one: warm_all waits on its own two children, so only warm_all
    # itself is left unreaped (verified by `ps` in a running container). The
    # alternative is keeping a shell as PID 1, which would change what `kill 1`
    # means in a container whose shutdown path relies on cao-server being PID 1.
    echo "[cao-entrypoint] warming providers in the background (readiness will not wait)"
    warm_all &
    ;;
  *)
    warm_all
    ;;
esac

echo "[cao-entrypoint] starting cao-server on ${BIND_HOST}:${PORT}"
exec cao-server --host "${BIND_HOST}" --port "${PORT}"
